FROM apache/airflow:2.8.2-python3.10
USER root

# Install OpenJDK-17
RUN apt update && \
    apt-get install -y openjdk-17-jdk ant && \
    apt-get clean;

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

USER airflow

COPY ./dags/requirements_airflow.txt /
RUN pip install -r /requirements_airflow.txt

